import asyncio
import base64
import json
import os
import platform
import queue
import secrets
import stat
import shutil
import subprocess
import sys
import threading
import time
import tkinter as tk
import tkinter.font as tkfont
import urllib.request
from pathlib import Path
from tkinter import messagebox, scrolledtext

from aiohttp import WSMsgType, web


APP_DIR = Path(__file__).resolve().parent
BIN_DIR = APP_DIR / "bin"
GENERATED_DIR = APP_DIR / "generated"
DEFAULT_CONTROL_PORT = 8765
DEFAULT_PROXY_PORT = 10022
DEFAULT_PROXY_HOST = "127.0.0.1"
DEFAULT_PROXY_TARGET_PORT = 2222
UNSET = object()


NOTEBOOK_TEMPLATE = r'''# Auto-generated by kaggle_tunnel_app.py
# Run this notebook cell on the remote machine that should connect back to the PC.
# After it starts, connect from the PC with:
#   ssh -p 10022 notebook@127.0.0.1
# Password:
#   the same Shared token shown in the PC app

import asyncio
import base64
import importlib
import json
import os
import shlex
import socket
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

def ensure_package(module_name: str, package_name=None):
    try:
        return importlib.import_module(module_name)
    except ImportError:
        subprocess.check_call([sys.executable, "-m", "pip", "install", package_name or module_name])
        return importlib.import_module(module_name)


nest_asyncio = ensure_package("nest_asyncio")
websockets = ensure_package("websockets")
asyncssh = ensure_package("asyncssh")

nest_asyncio.apply()

CONTROL_URL = {control_url!r}
CONTROL_TOKEN = {control_token!r}
EMBEDDED_SSH_HOST = "127.0.0.1"
EMBEDDED_SSH_PORT = 2222
EMBEDDED_SSH_USER = "notebook"
HOST_KEY_PATH = Path("/kaggle/working/.kaggle_tunnel/ssh_host_key")


def _b64encode(data: bytes) -> str:
    return base64.b64encode(data).decode("ascii")


def _b64decode(text: str) -> bytes:
    return base64.b64decode(text.encode("ascii"))


@dataclass
class TcpHandle:
    reader: asyncio.StreamReader
    writer: asyncio.StreamWriter
    pump_task: asyncio.Task


class EmbeddedSSHServer(asyncssh.SSHServer):
    def connection_made(self, conn):
        peer = conn.get_extra_info("peername")
        print(f"Embedded SSH connection from: {{peer}}")

    def begin_auth(self, username):
        return True

    def password_auth_supported(self):
        return True

    def validate_password(self, username, password):
        return username == EMBEDDED_SSH_USER and password == CONTROL_TOKEN


async def handle_ssh_client(process):
    env = os.environ.copy()
    if getattr(process, "term_type", None):
        env["TERM"] = process.term_type

    if process.command:
        child = subprocess.Popen(
            process.command,
            shell=True,
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            env=env,
        )
    else:
        shell = env.get("SHELL") or "/bin/bash"
        shell_argv = [shell, "-i"]
        child = subprocess.Popen(
            shell_argv,
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            env=env,
        )

    await process.redirect(
        stdin=child.stdin,
        stdout=child.stdout,
        stderr=child.stderr,
    )
    returncode = await asyncio.to_thread(child.wait)
    process.exit(returncode)


def ensure_embedded_ssh_host_key() -> str:
    HOST_KEY_PATH.parent.mkdir(parents=True, exist_ok=True)
    if not HOST_KEY_PATH.exists():
        host_key = asyncssh.generate_private_key("ssh-rsa")
        host_key.write_private_key(str(HOST_KEY_PATH))
        print(f"Generated embedded SSH host key at {{HOST_KEY_PATH}}")
    return str(HOST_KEY_PATH)


async def start_embedded_ssh_server():
    host_key_path = ensure_embedded_ssh_host_key()
    await asyncssh.create_server(
        EmbeddedSSHServer,
        EMBEDDED_SSH_HOST,
        EMBEDDED_SSH_PORT,
        server_host_keys=[host_key_path],
        process_factory=handle_ssh_client,
    )
    print(
        f"Embedded SSH server listening on {{EMBEDDED_SSH_HOST}}:{{EMBEDDED_SSH_PORT}} "
        f"for user {{EMBEDDED_SSH_USER}}"
    )
    print("SSH password is the Shared token from the PC app.")
    print(f"SSH host key path: {{host_key_path}}")


class RemoteAgent:
    def __init__(self, control_url: str, control_token: str):
        self.control_url = control_url
        self.control_token = control_token
        self.websocket = None
        self.tcp_handles = {{}}

    async def send(self, payload):
        if self.websocket is not None:
            await self.websocket.send(json.dumps(payload))

    async def handle_run_command(self, payload):
        request_id = payload["request_id"]
        process = await asyncio.create_subprocess_shell(
            payload["command"],
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, stderr = await process.communicate()
        await self.send(
            {{
                "type": "command_result",
                "request_id": request_id,
                "returncode": process.returncode,
                "stdout": stdout.decode("utf-8", errors="replace"),
                "stderr": stderr.decode("utf-8", errors="replace"),
            }}
        )

    async def _tcp_pump(self, connection_id: str, reader: asyncio.StreamReader):
        try:
            while True:
                chunk = await reader.read(65536)
                if not chunk:
                    break
                await self.send(
                    {{
                        "type": "tcp_data",
                        "connection_id": connection_id,
                        "data": _b64encode(chunk),
                    }}
                )
        finally:
            await self.close_tcp(connection_id)

    async def handle_tcp_open(self, payload):
        connection_id = payload["connection_id"]
        try:
            reader, writer = await asyncio.open_connection(payload["host"], int(payload["port"]))
            self.tcp_handles[connection_id] = TcpHandle(
                reader=reader,
                writer=writer,
                pump_task=asyncio.create_task(self._tcp_pump(connection_id, reader)),
            )
            await self.send({{"type": "tcp_opened", "connection_id": connection_id}})
        except Exception as exc:
            await self.send(
                {{
                    "type": "tcp_closed",
                    "connection_id": connection_id,
                    "error": str(exc),
                }}
            )

    async def handle_tcp_data(self, payload):
        handle = self.tcp_handles.get(payload["connection_id"])
        if handle is None:
            return
        handle.writer.write(_b64decode(payload["data"]))
        await handle.writer.drain()

    async def close_tcp(self, connection_id: str):
        handle = self.tcp_handles.pop(connection_id, None)
        if handle is None:
            return
        handle.writer.close()
        try:
            await handle.writer.wait_closed()
        except Exception:
            pass
        if not handle.pump_task.done():
            handle.pump_task.cancel()
        await self.send({{"type": "tcp_closed", "connection_id": connection_id}})

    async def handle_message(self, payload):
        message_type = payload.get("type")
        if message_type == "run_command":
            await self.handle_run_command(payload)
        elif message_type == "tcp_open":
            await self.handle_tcp_open(payload)
        elif message_type == "tcp_data":
            await self.handle_tcp_data(payload)
        elif message_type == "tcp_close":
            await self.close_tcp(payload["connection_id"])

    async def run(self):
        headers = [("x-kaggle-tunnel-token", self.control_token)]
        while True:
            try:
                async with websockets.connect(
                    self.control_url,
                    additional_headers=headers,
                    ping_interval=20,
                    ping_timeout=20,
                    max_size=None,
                ) as websocket:
                    self.websocket = websocket
                    await self.send(
                        {{
                            "type": "hello",
                            "hostname": socket.gethostname(),
                            "python": sys.version,
                            "platform": sys.platform,
                            "ssh_user": EMBEDDED_SSH_USER,
                            "ssh_host": EMBEDDED_SSH_HOST,
                            "ssh_port": EMBEDDED_SSH_PORT,
                        }}
                    )
                    async for raw in websocket:
                        await self.handle_message(json.loads(raw))
            except Exception as exc:
                print(f"remote agent reconnecting after error: {{exc}}")
                await asyncio.sleep(2)
            finally:
                self.websocket = None


async def main():
    await start_embedded_ssh_server()
    print("Remote notebook agent started. Leave this cell running.")
    await RemoteAgent(CONTROL_URL, CONTROL_TOKEN).run()


asyncio.get_event_loop().run_until_complete(main())
'''


def find_cloudflared() -> Path | None:
    system = platform.system().lower()
    if system == "windows":
        candidates = [
            str(BIN_DIR / "cloudflared.exe"),
            shutil.which("cloudflared"),
            str(BIN_DIR / "cloudflared"),
        ]
    else:
        candidates = [
            str(BIN_DIR / "cloudflared"),
            shutil.which("cloudflared"),
            str(BIN_DIR / "cloudflared.exe"),
        ]
    for candidate in candidates:
        if candidate and Path(candidate).exists():
            return Path(candidate)
    return None


def get_cloudflared_download_info() -> tuple[str, Path]:
    system = platform.system().lower()
    machine = platform.machine().lower()

    if system == "windows":
        filename = "cloudflared-windows-arm64.exe" if "arm" in machine else "cloudflared-windows-amd64.exe"
        target = BIN_DIR / "cloudflared.exe"
    elif system == "linux":
        if any(token in machine for token in ("aarch64", "arm64")):
            filename = "cloudflared-linux-arm64"
        else:
            filename = "cloudflared-linux-amd64"
        target = BIN_DIR / "cloudflared"
    elif system == "darwin":
        if any(token in machine for token in ("arm64", "aarch64")):
            filename = "cloudflared-darwin-arm64.tgz"
        else:
            filename = "cloudflared-darwin-amd64.tgz"
        raise RuntimeError(
            "Automatic cloudflared download is currently implemented for Windows and Linux. "
            f"Please install cloudflared manually for macOS and set its path in the app. Suggested asset: {filename}"
        )
    else:
        raise RuntimeError(f"Unsupported operating system for automatic cloudflared download: {platform.system()}")

    url = f"https://github.com/cloudflare/cloudflared/releases/latest/download/{filename}"
    return url, target


def download_cloudflared(log_callback):
    BIN_DIR.mkdir(parents=True, exist_ok=True)
    url, target = get_cloudflared_download_info()
    log_callback(f"Downloading cloudflared from {url}")
    with urllib.request.urlopen(url) as response, open(target, "wb") as output:
        output.write(response.read())
    if platform.system().lower() != "windows":
        target.chmod(target.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return target


class TunnelRuntime:
    def __init__(self, log_callback, state_callback):
        self.log = log_callback
        self.state_callback = state_callback
        self.loop = None
        self.loop_thread = None
        self.runner = None
        self.site = None
        self.control_port = None
        self.token = None
        self.public_url = None
        self.ws = None
        self.cloudflared_process = None
        self.proxy_server = None
        self.proxy_clients = {}
        self.remote_info = {}

    async def _close_writer_quietly(self, writer):
        writer.close()
        try:
            await writer.wait_closed()
        except (ConnectionResetError, BrokenPipeError, OSError):
            pass
        except Exception:
            pass

    def ensure_loop(self):
        if self.loop is not None:
            return
        self.loop = asyncio.new_event_loop()
        self.loop_thread = threading.Thread(target=self._run_loop, daemon=True)
        self.loop_thread.start()

    def _run_loop(self):
        asyncio.set_event_loop(self.loop)
        self.loop.run_forever()

    def run_coro(self, coro):
        self.ensure_loop()
        return asyncio.run_coroutine_threadsafe(coro, self.loop)

    async def start_server(self, control_port: int, token: str):
        if self.runner is not None:
            await self.stop_server()
        self.control_port = control_port
        self.token = token
        app = web.Application()
        app.router.add_get("/healthz", self.handle_health)
        app.router.add_get("/ws", self.handle_ws)
        self.runner = web.AppRunner(app)
        await self.runner.setup()
        self.site = web.TCPSite(self.runner, "127.0.0.1", control_port)
        await self.site.start()
        self.log(f"Control server listening on 127.0.0.1:{control_port}")

    async def stop_server(self):
        if self.proxy_server is not None:
            self.proxy_server.close()
            await self.proxy_server.wait_closed()
            self.proxy_server = None
        for client in list(self.proxy_clients.values()):
            client["writer"].close()
        self.proxy_clients.clear()
        if self.ws is not None:
            await self.ws.close()
            self.ws = None
        if self.site is not None:
            await self.site.stop()
            self.site = None
        if self.runner is not None:
            await self.runner.cleanup()
            self.runner = None

    async def handle_health(self, request):
        return web.json_response(
            {
                "ok": True,
                "connected": self.ws is not None,
                "public_url": self.public_url,
                "remote_info": self.remote_info,
            }
        )

    async def handle_ws(self, request):
        provided_token = request.query.get("token") or request.headers.get("x-kaggle-tunnel-token")
        if provided_token != self.token:
            return web.Response(status=403, text="invalid token")
        ws = web.WebSocketResponse(max_msg_size=0)
        await ws.prepare(request)
        if self.ws is not None:
            await self.ws.close(code=4000, message=b"replaced")
        self.ws = ws
        self.state_callback(remote_connected=True)
        self.log("Remote notebook connected.")
        async for message in ws:
            if message.type == WSMsgType.TEXT:
                await self.process_remote_message(json.loads(message.data))
            elif message.type == WSMsgType.ERROR:
                self.log(f"Websocket error: {ws.exception()}")
        self.ws = None
        self.remote_info = {}
        self.state_callback(remote_connected=False, remote_info={})
        self.log("Remote notebook disconnected.")
        return ws

    async def process_remote_message(self, payload):
        message_type = payload.get("type")
        if message_type == "hello":
            self.remote_info = payload
            self.state_callback(remote_connected=True, remote_info=payload)
            self.log(
                f"Notebook hello from {payload.get('hostname', 'unknown')} "
                f"({payload.get('platform', 'unknown')})"
            )
            if payload.get("ssh_port"):
                self.log(
                    "Embedded SSH ready on notebook side: "
                    f"{payload.get('ssh_host', '127.0.0.1')}:{payload.get('ssh_port')} "
                    f"user={payload.get('ssh_user', 'notebook')}"
                )
        elif message_type == "command_result":
            request_id = payload.get("request_id")
            self.log(
                f"[command {request_id}] rc={payload.get('returncode')}\n"
                f"{payload.get('stdout', '')}{payload.get('stderr', '')}"
            )
        elif message_type == "tcp_data":
            client = self.proxy_clients.get(payload["connection_id"])
            if client:
                client["writer"].write(base64.b64decode(payload["data"]))
                await client["writer"].drain()
        elif message_type == "tcp_opened":
            self.log(f"Remote proxy opened: {payload['connection_id']}")
        elif message_type == "tcp_closed":
            connection_id = payload["connection_id"]
            client = self.proxy_clients.pop(connection_id, None)
            if client:
                await self._close_writer_quietly(client["writer"])
            self.log(f"Remote proxy closed: {connection_id}")
            if "error" in payload:
                self.log(f"Remote proxy error for {connection_id}: {payload['error']}")
        elif message_type == "ssh_status":
            self.log(f"SSH tunnel status: {json.dumps(payload, indent=2)}")
        elif message_type == "log":
            self.log(payload.get("message", "remote log"))

    async def send(self, payload):
        if self.ws is None:
            raise RuntimeError("Remote notebook is not connected.")
        await self.ws.send_json(payload)

    def start_cloudflared(self, cloudflared_path: Path):
        if self.control_port is None:
            raise RuntimeError("Start the control server first.")
        if self.cloudflared_process and self.cloudflared_process.poll() is None:
            raise RuntimeError("cloudflared is already running.")
        command = [
            str(cloudflared_path),
            "tunnel",
            "--url",
            f"http://127.0.0.1:{self.control_port}",
            "--no-autoupdate",
        ]
        self.log(f"Starting cloudflared: {' '.join(command)}")
        self.cloudflared_process = subprocess.Popen(
            command,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1,
        )
        threading.Thread(target=self._watch_cloudflared_output, daemon=True).start()

    def _watch_cloudflared_output(self):
        assert self.cloudflared_process is not None
        for line in self.cloudflared_process.stdout:
            line = line.rstrip()
            self.log(f"[cloudflared] {line}")
            if "trycloudflare.com" in line and self.public_url is None:
                for part in line.split():
                    if part.startswith("https://") and "trycloudflare.com" in part:
                        self.public_url = part
                        self.state_callback(public_url=self.public_url)
                        self.log(f"Tunnel URL ready: {self.public_url}")
                        break
        return_code = self.cloudflared_process.wait()
        self.log(f"cloudflared exited with code {return_code}")
        self.public_url = None
        self.state_callback(public_url=None)

    def stop_cloudflared(self):
        if self.cloudflared_process and self.cloudflared_process.poll() is None:
            self.cloudflared_process.terminate()
            try:
                self.cloudflared_process.wait(timeout=10)
            except subprocess.TimeoutExpired:
                self.cloudflared_process.kill()
        self.cloudflared_process = None
        self.public_url = None
        self.state_callback(public_url=None)

    async def start_proxy(self, bind_port: int, target_host: str, target_port: int):
        if self.proxy_server is not None:
            self.proxy_server.close()
            await self.proxy_server.wait_closed()
        self.proxy_server = await asyncio.start_server(
            lambda reader, writer: self.handle_proxy_client(reader, writer, target_host, target_port),
            "127.0.0.1",
            bind_port,
        )
        self.log(f"Local proxy listening on 127.0.0.1:{bind_port} -> {target_host}:{target_port}")

    async def stop_proxy(self):
        if self.proxy_server is not None:
            self.proxy_server.close()
            await self.proxy_server.wait_closed()
            self.proxy_server = None
            self.log("Local proxy stopped.")

    async def handle_proxy_client(self, reader, writer, target_host: str, target_port: int):
        connection_id = secrets.token_hex(8)
        self.proxy_clients[connection_id] = {"writer": writer}
        await self.send(
            {
                "type": "tcp_open",
                "connection_id": connection_id,
                "host": target_host,
                "port": target_port,
            }
        )
        self.log(f"Accepted local proxy client {connection_id}")
        try:
            while True:
                chunk = await reader.read(65536)
                if not chunk:
                    break
                await self.send(
                    {
                        "type": "tcp_data",
                        "connection_id": connection_id,
                        "data": base64.b64encode(chunk).decode("ascii"),
                    }
                )
        except (ConnectionResetError, BrokenPipeError, OSError) as exc:
            self.log(f"Local proxy client {connection_id} disconnected: {exc}")
        finally:
            try:
                await self.send({"type": "tcp_close", "connection_id": connection_id})
            except Exception:
                pass
            self.proxy_clients.pop(connection_id, None)
            await self._close_writer_quietly(writer)

    def generate_notebook(self):
        if not self.public_url:
            raise RuntimeError("Tunnel URL is not ready yet.")
        GENERATED_DIR.mkdir(parents=True, exist_ok=True)
        control_url = self.public_url.replace("https://", "wss://").rstrip("/") + f"/ws?token={self.token}"
        notebook_code = NOTEBOOK_TEMPLATE.format(
            control_url=control_url,
            control_token=self.token,
        )
        py_target = GENERATED_DIR / "remote_notebook_cell.py"
        ipynb_target = GENERATED_DIR / "remote_notebook.ipynb"
        py_target.write_text(notebook_code, encoding="utf-8")
        notebook_payload = {
            "cells": [
                {
                    "cell_type": "code",
                    "execution_count": None,
                    "metadata": {},
                    "outputs": [],
                    "source": notebook_code.splitlines(keepends=True),
                }
            ],
            "metadata": {
                "kernelspec": {
                    "display_name": "Python 3",
                    "language": "python",
                    "name": "python3",
                },
                "language_info": {
                    "name": "python",
                },
            },
            "nbformat": 4,
            "nbformat_minor": 5,
        }
        ipynb_target.write_text(json.dumps(notebook_payload, indent=2), encoding="utf-8")
        return py_target, ipynb_target, notebook_code

    def build_notebook_cell_code(self):
        if not self.public_url:
            raise RuntimeError("Tunnel URL is not ready yet.")
        control_url = self.public_url.replace("https://", "wss://").rstrip("/") + f"/ws?token={self.token}"
        return NOTEBOOK_TEMPLATE.format(
            control_url=control_url,
            control_token=self.token,
        )

    def build_agent_prompt(self, local_bind_port: int, remote_host: str, remote_port: int):
        if not self.public_url:
            raise RuntimeError("Tunnel URL is not ready yet.")
        token = self.token or ""
        ssh_user = self.remote_info.get("ssh_user", "notebook")
        prompt = f"""Use this remote execution endpoint for shell work.

Connection details:
- Transport: SSH over a local proxy created by the PC app
- Host: 127.0.0.1
- Port: {local_bind_port}
- Username: {ssh_user}
- Password: {token}

How this environment works:
- The actual compute environment is a notebook server connected back to the PC through Cloudflare Tunnel.
- The local proxy forwards SSH traffic to a Python-based SSH server running inside the notebook.
- Treat this as the execution environment for commands, file inspection, and code edits on the remote notebook side.

Connection requirements:
- Disable strict host key prompts or auto-accept the host key.
- If an SSH client asks for authentication, use the password above.
- Prefer non-interactive shell commands when possible.
- Verify the session first with a simple command like `pwd` or `python --version`.

Operational notes:
- Keep commands scoped to the connected remote environment.
- If the SSH connection fails, assume the notebook cell may not be running or the proxy may not be started.
- The PC app is expected to expose the proxy on 127.0.0.1:{local_bind_port}, forwarding to {remote_host}:{remote_port}.

Suggested first command:
- `python --version`
"""
        return prompt


class KaggleTunnelWindow:
    def __init__(self):
        self.root = tk.Tk()
        self.ui_scale = self.configure_display_scaling()
        self.root.title("Kaggle Tunnel Controller")
        self.root.geometry(f"{int(980 * self.ui_scale)}x{int(760 * self.ui_scale)}")
        self.root.minsize(int(900 * self.ui_scale), int(700 * self.ui_scale))

        self.log_queue = queue.Queue()
        self.runtime = TunnelRuntime(self.enqueue_log, self.on_runtime_state)
        self.current_public_url = ""
        self.remote_connected = False
        self.remote_info = {}
        self.active_ssh_request = None

        self.build_ui()
        self.root.after(200, self.flush_logs)
        self.root.protocol("WM_DELETE_WINDOW", self.on_destroy)

    def configure_display_scaling(self) -> float:
        scale_override = os.environ.get("KAGGLE_TUNNEL_UI_SCALE", "").strip()
        if scale_override:
            try:
                ui_scale = max(1.0, float(scale_override))
            except ValueError:
                ui_scale = 1.0
        elif sys.platform.startswith("linux"):
            ui_scale = self._detect_linux_ui_scale()
        else:
            ui_scale = 1.0

        if ui_scale > 1.0:
            try:
                current = float(self.root.tk.call("tk", "scaling"))
                self.root.tk.call("tk", "scaling", max(current, current * ui_scale))
            except Exception:
                pass
            self._scale_default_fonts(ui_scale)
        return ui_scale

    def _detect_linux_ui_scale(self) -> float:
        try:
            screen_width_px = self.root.winfo_screenwidth()
            screen_width_mm = self.root.winfo_screenmmwidth()
            if screen_width_px > 0 and screen_width_mm > 0:
                dpi = screen_width_px / (screen_width_mm / 25.4)
                if dpi >= 170:
                    return 1.6
                if dpi >= 140:
                    return 1.4
                if dpi >= 115:
                    return 1.2
        except Exception:
            pass
        return 1.25

    def _scale_default_fonts(self, ui_scale: float):
        for font_name in (
            "TkDefaultFont",
            "TkTextFont",
            "TkMenuFont",
            "TkHeadingFont",
            "TkCaptionFont",
            "TkSmallCaptionFont",
            "TkIconFont",
            "TkTooltipFont",
        ):
            try:
                font = tkfont.nametofont(font_name)
            except tk.TclError:
                continue
            size = font.cget("size")
            if not isinstance(size, int) or size == 0:
                continue
            scaled_size = max(10, int(round(abs(size) * ui_scale)))
            font.configure(size=-scaled_size if size < 0 else scaled_size)

    def build_ui(self):
        outer = tk.Frame(self.root, padx=12, pady=12)
        outer.pack(fill="both", expand=True)
        outer.grid_columnconfigure(0, weight=1)
        outer.grid_rowconfigure(5, weight=1)

        tunnel_frame = tk.LabelFrame(outer, text="Tunnel", padx=10, pady=10)
        tunnel_frame.grid(row=0, column=0, sticky="ew")
        for column in range(3):
            tunnel_frame.grid_columnconfigure(column, weight=1 if column == 1 else 0)

        self.cloudflared_var = tk.StringVar(value=str(find_cloudflared() or ""))
        self.control_port_var = tk.StringVar(value=str(DEFAULT_CONTROL_PORT))
        self.token_var = tk.StringVar(value=secrets.token_urlsafe(24))
        self.tunnel_url_var = tk.StringVar()
        self.remote_state_var = tk.StringVar(value="Remote: disconnected")

        self._add_labeled_entry(tunnel_frame, 0, "cloudflared path", self.cloudflared_var, width=72)
        tk.Button(tunnel_frame, text="Download cloudflared", command=self.on_install_cloudflared).grid(
            row=0, column=2, sticky="ew", padx=(8, 0)
        )
        self._add_labeled_entry(tunnel_frame, 1, "Control port", self.control_port_var)
        self._add_labeled_entry(tunnel_frame, 2, "Shared token", self.token_var)
        self._add_labeled_entry(
            tunnel_frame,
            3,
            "Tunnel URL",
            self.tunnel_url_var,
            state="readonly",
            width=72,
        )
        tk.Label(tunnel_frame, textvariable=self.remote_state_var, anchor="w").grid(
            row=4, column=1, columnspan=2, sticky="ew", pady=(4, 0)
        )

        tunnel_buttons = tk.Frame(outer)
        tunnel_buttons.grid(row=1, column=0, sticky="w", pady=(10, 0))
        for index, (label, handler) in enumerate(
            [
                ("Start Tunnel", self.on_start_tunnel),
                ("Stop Tunnel", self.on_stop_tunnel),
                ("Copy Cell Code", self.on_copy_cell_code),
                ("Copy Agent Prompt", self.on_copy_agent_prompt),
            ]
        ):
            tk.Button(tunnel_buttons, text=label, command=handler).grid(row=0, column=index, padx=(0, 8))

        proxy_frame = tk.LabelFrame(outer, text="TCP / SSH Proxy", padx=10, pady=10)
        proxy_frame.grid(row=2, column=0, sticky="ew", pady=(10, 0))
        for column in range(3):
            proxy_frame.grid_columnconfigure(column, weight=1 if column == 1 else 0)

        self.proxy_bind_port_var = tk.StringVar(value=str(DEFAULT_PROXY_PORT))
        self.proxy_target_host_var = tk.StringVar(value=DEFAULT_PROXY_HOST)
        self.proxy_target_port_var = tk.StringVar(value=str(DEFAULT_PROXY_TARGET_PORT))

        self._add_labeled_entry(proxy_frame, 0, "Local bind port", self.proxy_bind_port_var)
        self._add_labeled_entry(proxy_frame, 1, "Remote target host", self.proxy_target_host_var)
        self._add_labeled_entry(proxy_frame, 2, "Remote target port", self.proxy_target_port_var)
        tk.Button(proxy_frame, text="Start Proxy", command=self.on_start_proxy).grid(
            row=0, column=2, sticky="ew", padx=(8, 0)
        )
        tk.Button(proxy_frame, text="Stop Proxy", command=self.on_stop_proxy).grid(
            row=1, column=2, sticky="ew", padx=(8, 0)
        )

        ssh_frame = tk.LabelFrame(outer, text="Embedded SSH", padx=10, pady=10)
        ssh_frame.grid(row=3, column=0, sticky="ew", pady=(10, 0))
        ssh_frame.grid_columnconfigure(0, weight=1)
        self.ssh_hint_var = tk.StringVar(
            value=(
                "Run the copied notebook cell first. Then connect from this PC with:\n"
                "ssh -p 10022 notebook@127.0.0.1\n"
                "Password: use the Shared token"
            )
        )
        tk.Label(ssh_frame, textvariable=self.ssh_hint_var, justify="left", anchor="w").grid(
            row=0, column=0, sticky="ew"
        )

        command_frame = tk.LabelFrame(outer, text="Remote Command", padx=10, pady=10)
        command_frame.grid(row=4, column=0, sticky="ew", pady=(10, 0))
        command_frame.grid_columnconfigure(0, weight=1)
        self.command_var = tk.StringVar()
        command_entry = tk.Entry(command_frame, textvariable=self.command_var)
        command_entry.grid(row=0, column=0, sticky="ew")
        tk.Button(command_frame, text="Run", command=self.on_run_command).grid(row=0, column=1, padx=(8, 0))

        log_frame = tk.LabelFrame(outer, text="Log", padx=10, pady=10)
        log_frame.grid(row=5, column=0, sticky="nsew", pady=(10, 0))
        log_frame.grid_columnconfigure(0, weight=1)
        log_frame.grid_rowconfigure(0, weight=1)
        self.log_widget = scrolledtext.ScrolledText(log_frame, wrap="word", state="disabled")
        self.log_widget.grid(row=0, column=0, sticky="nsew")

    def _add_labeled_entry(self, parent, row, label, variable, state="normal", width=40):
        tk.Label(parent, text=label, anchor="w").grid(row=row, column=0, sticky="w", pady=4)
        entry = tk.Entry(parent, textvariable=variable, width=width)
        if state != "normal":
            entry.configure(state=state)
        entry.grid(row=row, column=1, sticky="ew", pady=4)
        return entry

    def enqueue_log(self, message: str):
        timestamp = time.strftime("%H:%M:%S")
        self.log_queue.put(f"[{timestamp}] {message}")

    def flush_logs(self):
        while True:
            try:
                line = self.log_queue.get_nowait()
            except queue.Empty:
                break
            self.log_widget.configure(state="normal")
            self.log_widget.insert("end", line + "\n")
            self.log_widget.see("end")
            self.log_widget.configure(state="disabled")
        self.root.after(200, self.flush_logs)

    def on_runtime_state(self, public_url=UNSET, remote_connected=UNSET, remote_info=UNSET):
        def apply_state():
            if public_url is not UNSET:
                self.current_public_url = public_url or ""
                self.tunnel_url_var.set(self.current_public_url)
            if remote_connected is not UNSET:
                self.remote_connected = remote_connected
            if remote_info is not UNSET:
                self.remote_info = remote_info
            if self.remote_connected:
                hostname = self.remote_info.get("hostname", "connected")
                self.remote_state_var.set(f"Remote: connected ({hostname})")
                ssh_user = self.remote_info.get("ssh_user", "notebook")
                self.ssh_hint_var.set(
                    "Run the copied notebook cell first. Then connect from this PC with:\n"
                    f"ssh -p {self.proxy_bind_port_var.get() or DEFAULT_PROXY_PORT} {ssh_user}@127.0.0.1\n"
                    "Password: use the Shared token"
                )
            else:
                self.remote_state_var.set("Remote: disconnected")

        self.root.after(0, apply_state)

    def parse_int(self, raw_value: str, label: str) -> int:
        try:
            return int(raw_value.strip())
        except ValueError as exc:
            raise ValueError(f"{label} must be an integer.") from exc

    def show_error(self, message: str):
        messagebox.showerror("Operation failed", message, parent=self.root)

    def on_install_cloudflared(self, _button):
        def worker():
            try:
                target = download_cloudflared(self.enqueue_log)
                self.root.after(0, lambda: self.cloudflared_var.set(str(target)))
                self.enqueue_log(f"cloudflared downloaded to {target}")
            except Exception as exc:
                self.enqueue_log(f"Failed to download cloudflared: {exc}")
                self.root.after(0, lambda: self.show_error(str(exc)))

        threading.Thread(target=worker, daemon=True).start()

    def on_start_tunnel(self, _button=None):
        try:
            control_port = self.parse_int(self.control_port_var.get(), "Control port")
            token = self.token_var.get().strip()
            if not token:
                raise ValueError("Shared token is required.")
            cloudflared_path = Path(self.cloudflared_var.get().strip())
            if not cloudflared_path.exists():
                raise FileNotFoundError(
                    "cloudflared executable was not found. Download it first or set the correct path."
                )
        except Exception as exc:
            self.show_error(str(exc))
            return

        self.enqueue_log("Starting control server and Cloudflare tunnel.")

        def worker():
            try:
                self.runtime.run_coro(self.runtime.start_server(control_port, token)).result()
                self.runtime.start_cloudflared(cloudflared_path)
            except Exception as exc:
                self.enqueue_log(f"Failed to start tunnel: {exc}")
                self.root.after(0, lambda: self.show_error(str(exc)))

        threading.Thread(target=worker, daemon=True).start()

    def on_stop_tunnel(self, _button=None):
        self.enqueue_log("Stopping tunnel.")

        def worker():
            try:
                self.runtime.stop_cloudflared()
                self.runtime.run_coro(self.runtime.stop_server()).result()
            except Exception as exc:
                self.enqueue_log(f"Failed to stop tunnel cleanly: {exc}")

        threading.Thread(target=worker, daemon=True).start()

    def on_copy_cell_code(self, _button=None):
        self.enqueue_log("Copying notebook cell code with the current tunnel URL.")
        try:
            code = self.runtime.build_notebook_cell_code()
        except Exception as exc:
            self.show_error(str(exc))
            return

        try:
            self.root.clipboard_clear()
            self.root.clipboard_append(code)
            self.root.update_idletasks()
        except Exception:
            self.show_error("Clipboard copy failed.")
            return
        self.enqueue_log("Notebook cell code copied to clipboard.")

    def on_copy_agent_prompt(self, _button=None):
        self.enqueue_log("Copying LLM agent prompt for this execution server.")
        try:
            bind_port = self.parse_int(self.proxy_bind_port_var.get(), "Local bind port")
            target_port = self.parse_int(self.proxy_target_port_var.get(), "Remote target port")
            target_host = self.proxy_target_host_var.get().strip()
            if not target_host:
                raise ValueError("Remote target host is required.")
            prompt = self.runtime.build_agent_prompt(bind_port, target_host, target_port)
        except Exception as exc:
            self.show_error(str(exc))
            return

        try:
            self.root.clipboard_clear()
            self.root.clipboard_append(prompt)
            self.root.update_idletasks()
        except Exception:
            self.show_error("Clipboard copy failed.")
            return
        self.enqueue_log("LLM agent prompt copied to clipboard.")

    def on_start_proxy(self, _button=None):
        try:
            bind_port = self.parse_int(self.proxy_bind_port_var.get(), "Local bind port")
            target_port = self.parse_int(self.proxy_target_port_var.get(), "Remote target port")
            target_host = self.proxy_target_host_var.get().strip()
            if not target_host:
                raise ValueError("Remote target host is required.")
        except Exception as exc:
            self.show_error(str(exc))
            return

        self.enqueue_log(
            f"Starting local proxy on 127.0.0.1:{bind_port} forwarding to {target_host}:{target_port} from the notebook."
        )

        def worker():
            try:
                self.runtime.run_coro(self.runtime.start_proxy(bind_port, target_host, target_port)).result()
            except Exception as exc:
                self.enqueue_log(f"Failed to start proxy: {exc}")
                self.root.after(0, lambda: self.show_error(str(exc)))

        threading.Thread(target=worker, daemon=True).start()

    def on_stop_proxy(self, _button=None):
        self.enqueue_log("Stopping local proxy.")

        def worker():
            try:
                self.runtime.run_coro(self.runtime.stop_proxy()).result()
            except Exception as exc:
                self.enqueue_log(f"Failed to stop proxy: {exc}")

        threading.Thread(target=worker, daemon=True).start()

    def on_run_command(self, _button=None):
        command = self.command_var.get().strip()
        if not command:
            self.show_error("Enter a command to run on the notebook side.")
            return
        request_id = secrets.token_hex(6)
        self.enqueue_log(f"Dispatching command {request_id}: {command}")

        def worker():
            try:
                self.runtime.run_coro(
                    self.runtime.send(
                        {
                            "type": "run_command",
                            "request_id": request_id,
                            "command": command,
                        }
                    )
                ).result()
            except Exception as exc:
                self.enqueue_log(f"Failed to dispatch command: {exc}")
                self.root.after(0, lambda: self.show_error(str(exc)))

        threading.Thread(target=worker, daemon=True).start()

    def on_start_remote_ssh(self, _button=None):
        ssh_target = self.ssh_target_var.get().strip()
        if not ssh_target:
            self.show_error("SSH target is required.")
            return
        try:
            ssh_port = self.parse_int(self.ssh_port_var.get(), "SSH port")
        except Exception as exc:
            self.show_error(str(exc))
            return
        forwards = [item.strip() for item in self.ssh_forward_var.get().split(",") if item.strip()]
        extra_args = [item for item in self.ssh_extra_args_var.get().split() if item]
        request_id = secrets.token_hex(6)
        self.active_ssh_request = request_id
        self.enqueue_log(f"Starting remote SSH subprocess {request_id} for {ssh_target}")

        def worker():
            try:
                self.runtime.run_coro(
                    self.runtime.send(
                        {
                            "type": "start_ssh_tunnel",
                            "request_id": request_id,
                            "ssh_target": ssh_target,
                            "ssh_port": ssh_port,
                            "forwards": forwards,
                            "extra_args": extra_args,
                        }
                    )
                ).result()
            except Exception as exc:
                self.enqueue_log(f"Failed to start remote SSH subprocess: {exc}")
                self.root.after(0, lambda: self.show_error(str(exc)))

        threading.Thread(target=worker, daemon=True).start()

    def on_stop_remote_ssh(self, _button=None):
        if not self.active_ssh_request:
            self.show_error("No remote SSH tunnel has been started from this app session.")
            return
        request_id = self.active_ssh_request
        self.enqueue_log(f"Stopping remote SSH subprocess {request_id}")

        def worker():
            try:
                self.runtime.run_coro(
                    self.runtime.send(
                        {
                            "type": "stop_ssh_tunnel",
                            "request_id": request_id,
                        }
                    )
                ).result()
            except Exception as exc:
                self.enqueue_log(f"Failed to stop remote SSH subprocess: {exc}")
                self.root.after(0, lambda: self.show_error(str(exc)))

        threading.Thread(target=worker, daemon=True).start()

    def on_destroy(self, *_args):
        try:
            self.runtime.stop_cloudflared()
            self.runtime.run_coro(self.runtime.stop_server()).result(timeout=5)
        except Exception:
            pass
        self.root.destroy()

    def run(self):
        self.root.mainloop()


def main():
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    BIN_DIR.mkdir(parents=True, exist_ok=True)
    window = KaggleTunnelWindow()
    window.run()


if __name__ == "__main__":
    main()
