"""Notebook cell template for kaggle-tunnel (reversed-direction).

In this flow the **VM (notebook) runs the tunnel** — it starts an
embedded SSH server, a WebSocket proxy, and a cloudflared tunnel,
then registers in tunnelbroker.  The PC-side manager discovers the
instance and connects to it.

The cell:
  1. Installs required packages.
  2. Starts an embedded SSH server (asyncssh) on port 2222 capable of
     handling **multiple concurrent connections**.
  3. Starts an aiohttp WebSocket proxy that authenticates callers via
     the group bearer token and bridges WS ↔ local SSH server.
  4. Starts a **cloudflared tunnel** to expose the WS proxy publicly.
  5. Registers the tunnel URL + credentials in **tunnelbroker**.
  6. Keeps the tunnel alive; de-registers on shutdown / exception.

Authentication:
  - Only peers presenting the correct ``GROUP_TOKEN`` (via the
    ``x-kaggle-tunnel-token`` header or ``token`` query param) may
    open a WebSocket connection.  This ensures only group members
    can reach the embedded SSH server.

Render with::

    NOTEBOOK_CELL_TEMPLATE.format(
        instance_name=...,
        shared_secret=...,           # SSH password
        tunnelbroker_url=...,
        tunnelbroker_group=...,
        tunnelbroker_token=...,      # group bearer token (auth)
    )
"""

NOTEBOOK_CELL_TEMPLATE = r'''# Auto-generated by kaggle-tunnel (reversed-direction)
# VM runs its own tunnel. PC discovers via tunnelbroker and connects.
# Multiple concurrent SSH connections supported.
#
# After this cell starts, connect from the manager app.

import asyncio, base64, importlib, json, os, pty, shlex, shutil, socket
import struct, subprocess, sys, termios, time, traceback
from dataclasses import dataclass
from pathlib import Path


def ensure_package(m, pkg=None):
    try:
        return importlib.import_module(m)
    except ImportError:
        subprocess.check_call([sys.executable, "-m", "pip", "install", pkg or m])
        return importlib.import_module(m)


# ── Runtime deps (installed on first use) ──
ensure_package("nest_asyncio")
ensure_package("aiohttp")
websockets = ensure_package("websockets")
asyncssh = ensure_package("asyncssh")
import aiohttp
import aiohttp.web
import nest_asyncio

nest_asyncio.apply()

# ── Configuration (filled in by manager) ──
INSTANCE_NAME = {instance_name!r}
SHARED_SECRET = {shared_secret!r}          # SSH password
TUNNELBROKER_URL = {tunnelbroker_url!r}
TUNNELBROKER_GROUP = {tunnelbroker_group!r}
TUNNELBROKER_TOKEN = {tunnelbroker_token!r}  # group bearer token — auth gate

SSH_HOST = "127.0.0.1"
SSH_PORT = 2222
SSH_USER = "notebook"
WS_PORT = 8765
HOST_KEY_DIR = Path("/kaggle/working/.kaggle_tunnel")
HOST_KEY_PATH = HOST_KEY_DIR / "ssh_host_key"
CLOUDFLARED_HOME = HOST_KEY_DIR / "cloudflared-home"

os.environ.setdefault("NO_AUTOUPDATE", "1")


def _b64encode(d): return base64.b64encode(d).decode("ascii")
def _b64decode(t): return base64.b64decode(t)



# ── SSH server (handles multiple connections natively) ──

class KaggleSSHServer(asyncssh.SSHServer):
    def connection_made(self, conn):
        peer = conn.get_extra_info("peername", ("?", 0))
        print(f"[kgl] SSH connection from {{peer[0]}}:{{peer[1]}}")

    def begin_auth(self, _username):
        return True

    def password_auth_supported(self):
        return True

    def validate_password(self, username, password):
        ok = username == SSH_USER and password == SHARED_SECRET
        print(f"[kgl] SSH auth: user={{username}} -> {{'OK' if ok else 'REJECTED'}}")
        return ok

    def connection_lost(self, exc):
        print(f"[kgl] SSH client disconnected: {{exc or 'clean'}}")


async def handle_ssh_client(process):
    env = os.environ.copy()
    if getattr(process, "term_type", None):
        env["TERM"] = process.term_type
    ts = getattr(process, "term_size", None)

    def apply_pty_size(fd, size=None):
        s = size or ts or (80, 24)
        try:
            w, h = int(s[0]), int(s[1])
            import fcntl
            fcntl.ioctl(fd, termios.TIOCSWINSZ, struct.pack("HHHH", h, w, 0, 0))
        except Exception:
            pass

    def setup_child_pty(slave_fd):
        try:
            os.setsid()
        except Exception:
            pass
        try:
            import fcntl
            fcntl.ioctl(slave_fd, termios.TIOCSCTTY, 0)
        except Exception:
            pass

    if getattr(process, "term_type", None):
        master_fd, slave_fd = pty.openpty()
        apply_pty_size(slave_fd)
        shell = env.get("SHELL") or "/bin/bash"
        if os.path.basename(shell) == "bash":
            shell_argv = [shell, "--noprofile", "--norc", "-i"]
        else:
            shell_argv = [shell, "-i"]

        if process.command:
            child = subprocess.Popen(
                process.command, shell=True,
                stdin=slave_fd, stdout=slave_fd, stderr=slave_fd,
                env=env, close_fds=True,
                preexec_fn=lambda: setup_child_pty(slave_fd),
            )
        else:
            child = subprocess.Popen(
                shell_argv, stdin=slave_fd, stdout=slave_fd, stderr=slave_fd,
                env=env, close_fds=True,
                preexec_fn=lambda: setup_child_pty(slave_fd),
            )
        os.close(slave_fd)

        async def pump_ssh_to_pty():
            try:
                while True:
                    try:
                        chunk = await process.stdin.read(1024)
                    except asyncssh.TerminalSizeChanged as exc:
                        apply_pty_size(master_fd, exc.term_size)
                        continue
                    if not chunk:
                        break
                    if isinstance(chunk, str):
                        chunk = chunk.encode("utf-8", errors="replace")
                    await asyncio.to_thread(os.write, master_fd, chunk)
            except Exception:
                pass

        async def pump_pty_to_ssh():
            try:
                while True:
                    chunk = await asyncio.to_thread(os.read, master_fd, 65536)
                    if not chunk:
                        break
                    process.stdout.write(chunk)
                    await process.stdout.drain()
            except Exception:
                pass

        t1 = asyncio.create_task(pump_ssh_to_pty())
        t2 = asyncio.create_task(pump_pty_to_ssh())
        try:
            await asyncio.wait([t1, t2], return_when=asyncio.FIRST_COMPLETED)
        finally:
            for t in (t1, t2):
                if not t.done():
                    t.cancel()
            if child.poll() is None:
                child.terminate()
                try:
                    await asyncio.to_thread(child.wait)
                except Exception:
                    child.kill()
            os.close(master_fd)
        rc = child.returncode if child.returncode is not None else await asyncio.to_thread(child.wait)
        process.exit(rc)
        return

    child = subprocess.Popen(
        process.command or [env.get("SHELL", "/bin/bash"), "-i"],
        shell=bool(process.command),
        stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
        env=env,
    )
    await process.redirect(stdin=child.stdin, stdout=child.stdout, stderr=child.stderr)
    process.exit(await asyncio.to_thread(child.wait))


async def start_ssh():
    HOST_KEY_DIR.mkdir(parents=True, exist_ok=True)
    if not HOST_KEY_PATH.exists():
        asyncssh.generate_private_key("ssh-rsa").write_private_key(str(HOST_KEY_PATH))
    host_key = asyncssh.read_private_key(str(HOST_KEY_PATH))
    await asyncssh.create_server(
        KaggleSSHServer, SSH_HOST, SSH_PORT,
        server_host_keys=[str(HOST_KEY_PATH)],
        process_factory=handle_ssh_client, encoding=None,
    )
    print(f"[kgl] SSH on {{SSH_HOST}}:{{SSH_PORT}}  user={{SSH_USER}}  pass={{SHARED_SECRET}}")
    return {{
        "fingerprint": host_key.get_fingerprint(),
        "public_key": host_key.export_public_key().decode("ascii").strip(),
    }}


# ── WS proxy (authenticated, multi-connection) ──

class WSProxy:
    def __init__(self):
        self._conns: dict[str, tuple] = {{}}
        self._total_conns = 0

    async def handle(self, request):
        self._total_conns += 1
        cid = f"ws-{{self._total_conns}}"
        client_ip = request.remote or "?"
        print(f"[kgl] [{{cid}}] WS connection #{{self._total_conns}} from {{client_ip}}")
        ws = aiohttp.web.WebSocketResponse(max_msg_size=0)
        await ws.prepare(request)

        token = request.headers.get("x-kaggle-tunnel-token", "") or request.query.get("token", "")
        if TUNNELBROKER_TOKEN and token != TUNNELBROKER_TOKEN:
            print(f"[kgl] [{{cid}}] Auth REJECTED (token mismatch)")
            await ws.send_json({{"type": "error", "message": "invalid or missing group token"}})
            await ws.close()
            return ws

        print(f"[kgl] [{{cid}}] Auth OK, client={{client_ip}}, ua={{request.headers.get('User-Agent', '?')}}")

        await ws.send_json({{
            "type": "hello",
            "hostname": socket.gethostname(),
            "instance_name": INSTANCE_NAME,
            "ssh_user": SSH_USER,
            "ssh_port": SSH_PORT,
        }})

        try:
            async for msg in ws:
                if msg.type == aiohttp.WSMsgType.TEXT:
                    await self._route(ws, json.loads(msg.data), cid)
                elif msg.type == aiohttp.WSMsgType.ERROR:
                    print(f"[kgl] [{{cid}}] WS error: {{ws.exception()}}")
                    break
                elif msg.type == aiohttp.WSMsgType.CLOSE:
                    print(f"[kgl] [{{cid}}] WS closed by peer")
                    break
        except Exception as exc:
            print(f"[kgl] [{{cid}}] WS handler exception: {{exc}}")
        finally:
            stale = [conn_id for conn_id in list(self._conns.keys())]
            for conn_id in stale:
                if conn_id in self._conns:
                    self._close_tcp(conn_id)
            print(f"[kgl] [{{cid}}] WS connection closed, cleaned up {{len(stale)}} TCP conn(s)")
        return ws

    async def _route(self, ws, payload, cid):
        t = payload.get("type")
        conn_id = payload.get("connection_id", "?")
        if t == "tcp_open":
            print(f"[kgl] [{{cid}}] tcp_open request: conn={{conn_id}} host={{payload.get('host', '?')}} port={{payload.get('port', '?')}}")
            asyncio.create_task(self._proxy_tcp(ws, payload, cid))
        elif t == "tcp_data":
            size = len(_b64decode(payload.get("data", "")))
            await self._forward_tcp(payload, cid, size)
        elif t == "tcp_close":
            print(f"[kgl] [{{cid}}] tcp_close: conn={{conn_id}}")
            self._close_tcp(payload["connection_id"])
        elif t == "run_command":
            cmd = payload.get("command", "")[:80]
            print(f"[kgl] [{{cid}}] run_command: conn={{conn_id}} cmd={{cmd}}...")
            await self._run_cmd(ws, payload, cid)

    async def _proxy_tcp(self, ws, payload, cid):
        conn_id = payload["connection_id"]
        print(f"[kgl] [{{cid}}] Opening TCP to SSH server ({{SSH_HOST}}:{{SSH_PORT}}) ...")
        try:
            reader, writer = await asyncio.open_connection(SSH_HOST, SSH_PORT)
            print(f"[kgl] [{{cid}}] TCP to SSH opened OK")
        except Exception as exc:
            print(f"[kgl] [{{cid}}] TCP to SSH FAILED: {{exc}}")
            await ws.send_json({{"type": "tcp_closed", "connection_id": conn_id, "error": str(exc)}})
            return

        bytes_from_vm = 0

        async def pump():
            nonlocal bytes_from_vm
            try:
                while True:
                    chunk = await reader.read(65536)
                    if not chunk:
                        print(f"[kgl] [{{cid}}] SSH EOF, relayed {{bytes_from_vm}} bytes")
                        break
                    bytes_from_vm += len(chunk)
                    if bytes_from_vm <= 65536 or bytes_from_vm % 65536 < 65535:
                        pass  # avoid flooding logs
                    await ws.send_json({{"type": "tcp_data", "connection_id": conn_id, "data": _b64encode(chunk)}})
            except Exception as exc:
                print(f"[kgl] [{{cid}}] pump exception: {{exc}}")
            finally:
                await ws.send_json({{"type": "tcp_closed", "connection_id": conn_id}})
                print(f"[kgl] [{{cid}}] pump done, sent {{bytes_from_vm}} bytes to PC")

        task = asyncio.create_task(pump())
        self._conns[conn_id] = (writer, task)
        await ws.send_json({{"type": "tcp_opened", "connection_id": conn_id}})
        print(f"[kgl] [{{cid}}] tcp_opened sent to PC")

    async def _forward_tcp(self, payload, cid, size):
        entry = self._conns.get(payload["connection_id"])
        if not entry:
            print(f"[kgl] [{{cid}}] tcp_data for unknown conn {{payload['connection_id']}}, dropping {{size}} bytes")
            return
        writer, _ = entry
        writer.write(_b64decode(payload["data"]))
        await writer.drain()

    def _close_tcp(self, conn_id):
        entry = self._conns.pop(conn_id, None)
        if not entry:
            return
        writer, task = entry
        try:
            writer.close()
        except Exception:
            pass
        if not task.done():
            task.cancel()

    async def _run_cmd(self, ws, payload, cid):
        proc = await asyncio.create_subprocess_shell(
            payload["command"],
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        stdout, stderr = await proc.communicate()
        print(f"[kgl] [{{cid}}] command exit={{proc.returncode}}, stdout={{len(stdout)}}B, stderr={{len(stderr)}}B")
        await ws.send_json({{
            "type": "command_result",
            "request_id": payload["request_id"],
            "returncode": proc.returncode,
            "stdout": stdout.decode("utf-8", errors="replace"),
            "stderr": stderr.decode("utf-8", errors="replace"),
        }})


# ── cloudflared management ──

def _find_cloudflared() -> str | None:
    candidates = [shutil.which("cloudflared")]
    for c in candidates:
        if c and os.path.isfile(c):
            return c
    import urllib.request
    import stat as _stat
    import platform as _platform
    CLOUDFLARED_HOME.mkdir(parents=True, exist_ok=True)
    machine = _platform.machine().lower()
    arch = "arm64" if any(t in machine for t in ("aarch64", "arm64")) else "amd64"
    url = f"https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-{{arch}}"
    target = CLOUDFLARED_HOME / "cloudflared"
    print(f"[kgl] Downloading cloudflared from {{url}}")
    try:
        urllib.request.urlretrieve(url, target)
        target.chmod(target.stat().st_mode | _stat.S_IXUSR | _stat.S_IXGRP | _stat.S_IXOTH)
        print(f"[kgl] Downloaded to {{target}}")
        return str(target)
    except Exception as exc:
        print(f"[kgl] Download failed: {{exc}}")
        return None


async def start_cloudflared(bin_path: str, port: int) -> tuple:
    proc = await asyncio.create_subprocess_exec(
        bin_path, "tunnel", "--url", f"http://127.0.0.1:{{port}}",
        stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.STDOUT,
        env={{**os.environ, "HOME": str(CLOUDFLARED_HOME), "NO_AUTOUPDATE": "1"}},
    )
    url = None
    deadline = time.monotonic() + 60  # 60s total timeout
    while time.monotonic() < deadline:
        try:
            # Read line without per-line timeout; rely on outer deadline
            line = await asyncio.wait_for(proc.stdout.readline(), timeout=45)
        except asyncio.TimeoutError:
            continue  # still time left, keep trying
        if not line:
            break
        decoded = line.decode("utf-8", errors="replace")
        print(f"  {{decoded}}", end="")
        if ".trycloudflare.com" in decoded and not url:
            for word in decoded.split():
                if word.startswith("https://") and ".trycloudflare.com" in word:
                    url = word.rstrip(".")
                    break
        if url:
            break  # found it, no need to wait for more output
    if not url:
        raise RuntimeError("cloudflared did not produce a tunnel URL")
    print(f"[kgl] Tunnel URL: {{url}}")
    return proc, url


# ── Tunnelbroker ──

async def tb_register(public_url: str) -> None:
    if not TUNNELBROKER_URL:
        print("[kgl] tunnelbroker URL not set; skipping registration")
        return
    metadata = {{
        "hostname": socket.gethostname(),
        "platform": sys.platform,
        "instance_name": INSTANCE_NAME,
        "ssh_user": SSH_USER,
        "ssh_port": SSH_PORT,
        "tunnel_type": "ws_proxy",
        "version": "0.2.0",
    }}
    headers = {{"Content-Type": "application/json", "User-Agent": "kaggle-tunnel/0.2.0"}}
    if TUNNELBROKER_TOKEN:
        headers["Authorization"] = f"Bearer {{TUNNELBROKER_TOKEN}}"
    body = {{"peer": INSTANCE_NAME, "secret": SHARED_SECRET, "endpoint": public_url, "metadata": metadata}}
    url = f"{{TUNNELBROKER_URL.rstrip('/')}}/v1/peers?group={{TUNNELBROKER_GROUP}}"
    async with aiohttp.ClientSession(headers=headers) as s:
        async with s.post(url, json=body) as r:
            if r.ok:
                print(f"[kgl] Registered in tunnelbroker as '{{INSTANCE_NAME}}'")
            else:
                print(f"[kgl] tb register: {{r.status}} {{await r.text()}}")


async def tb_deregister() -> None:
    if not TUNNELBROKER_URL:
        return
    headers = {{"Content-Type": "application/json", "User-Agent": "kaggle-tunnel/0.2.0"}}
    if TUNNELBROKER_TOKEN:
        headers["Authorization"] = f"Bearer {{TUNNELBROKER_TOKEN}}"
    body = {{"secret": SHARED_SECRET}}
    url = f"{{TUNNELBROKER_URL.rstrip('/')}}/v1/peers/{{INSTANCE_NAME}}?group={{TUNNELBROKER_GROUP}}"
    try:
        async with aiohttp.ClientSession(headers=headers) as s:
            async with s.delete(url, json=body) as r:
                if r.ok:
                    print("[kgl] De-registered from tunnelbroker")
                else:
                    print(f"[kgl] tb deregister: {{r.status}} {{await r.text()}}")
    except Exception as exc:
        print(f"[kgl] tb deregister error: {{exc}}")


# ── Main ──

async def main():
    import platform as _platform
    print(f"{{'='*60}}")
    print(f"  VM Tunnel Instance: {{INSTANCE_NAME}}")
    print(f"{{'='*60}}")
    print(f"  SSH: {{SSH_USER}}@{{SSH_HOST}}:{{SSH_PORT}}  password={{SHARED_SECRET}}")
    if TUNNELBROKER_TOKEN:
        print(f"  Group token auth: enabled")
    print()

    host_key = await start_ssh()
    print()

    cf_bin = _find_cloudflared()
    if not cf_bin:
        raise RuntimeError("cloudflared not found; cannot create tunnel")
    print(f"[kgl] Using cloudflared: {{cf_bin}}")
    print()

    proxy = WSProxy()
    app = aiohttp.web.Application()
    app.router.add_get("/ws", proxy.handle)
    app.router.add_get("/healthz", lambda r: aiohttp.web.Response(text="ok"))
    runner = aiohttp.web.AppRunner(app)
    await runner.setup()
    site = aiohttp.web.TCPSite(runner, "127.0.0.1", WS_PORT)
    await site.start()
    print(f"[kgl] WS proxy on {{SSH_HOST}}:{{WS_PORT}} (authenticated via group token)")

    cf_proc, pub_url = await start_cloudflared(cf_bin, WS_PORT)
    print()
    await tb_register(pub_url)
    print()

    print(f"[kgl] Instance running. Keep this cell alive.")
    print(f"[kgl] Endpoint: {{pub_url}}/ws")
    print(f"[kgl] Auth: x-kaggle-tunnel-token header or ?token= query param")
    print()
    try:
        while True:
            await asyncio.sleep(21600)
            await tb_register(pub_url)
            print(f"[kgl] Refreshed tunnelbroker registration")
    except asyncio.CancelledError:
        pass
    except Exception:
        traceback.print_exc()
    finally:
        print("[kgl] Shutting down...")
        await tb_deregister()
        if cf_proc and cf_proc.returncode is None:
            cf_proc.terminate()
            try:
                await asyncio.wait_for(cf_proc.wait(), timeout=5)
            except asyncio.TimeoutError:
                cf_proc.kill()
        await runner.cleanup()
        print("[kgl] Instance stopped")


if __name__ == "__main__":
    try:
        asyncio.get_event_loop().run_until_complete(main())
    except KeyboardInterrupt:
        pass
    except Exception:
        traceback.print_exc()
        try:
            asyncio.get_event_loop().run_until_complete(tb_deregister())
        except Exception:
            pass
else:
    try:
        asyncio.get_event_loop().run_until_complete(main())
    except Exception:
        traceback.print_exc()

'''
